//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodSys.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodSys.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功！.
        /// </summary>
        public static string M00001I {
            get {
                return ResourceManager.GetString("M00001I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，请重试！.
        /// </summary>
        public static string M00002E {
            get {
                return ResourceManager.GetString("M00002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请至少选择一行记录！.
        /// </summary>
        public static string M00003E {
            get {
                return ResourceManager.GetString("M00003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最多只能选择一行记录！.
        /// </summary>
        public static string M00004E {
            get {
                return ResourceManager.GetString("M00004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要删除么？.
        /// </summary>
        public static string M00005A {
            get {
                return ResourceManager.GetString("M00005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除操作失败，请去确认该数据是否正在被使用！.
        /// </summary>
        public static string M00006E {
            get {
                return ResourceManager.GetString("M00006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改失败，请确认信息是否正确！.
        /// </summary>
        public static string M00007E {
            get {
                return ResourceManager.GetString("M00007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报废失败，此意向合同已是待缴费状态！.
        /// </summary>
        public static string M00008E {
            get {
                return ResourceManager.GetString("M00008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消操作成功！.
        /// </summary>
        public static string M00009I {
            get {
                return ResourceManager.GetString("M00009I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择失败，请稍后再试！.
        /// </summary>
        public static string M00010E {
            get {
                return ResourceManager.GetString("M00010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消选择失败，请稍后再试！.
        /// </summary>
        public static string M00011E {
            get {
                return ResourceManager.GetString("M00011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不存在！.
        /// </summary>
        public static string M10001E {
            get {
                return ResourceManager.GetString("M10001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码错误！.
        /// </summary>
        public static string M10002E {
            get {
                return ResourceManager.GetString("M10002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该用户当前状态不可登录！.
        /// </summary>
        public static string M10003E {
            get {
                return ResourceManager.GetString("M10003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名！.
        /// </summary>
        public static string M10004I {
            get {
                return ResourceManager.GetString("M10004I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择需要编辑的角色！.
        /// </summary>
        public static string M10005I {
            get {
                return ResourceManager.GetString("M10005I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择需要删除的角色！.
        /// </summary>
        public static string M10006I {
            get {
                return ResourceManager.GetString("M10006I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此企业下已有个人用户信息，无法做删除操作；请确保此企业下无个人用户信息后，再做删除操作！.
        /// </summary>
        public static string M10007E {
            get {
                return ResourceManager.GetString("M10007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您所要删除的企业中至少有一个企业已有个人用户信息；无法做删除操作，请删除该企业下的所有个人用户信息！.
        /// </summary>
        public static string M10008E {
            get {
                return ResourceManager.GetString("M10008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此部门下已有用户信息，无法做删除操作；请确保此部门下无用户信息后，再做删除操作！.
        /// </summary>
        public static string M10009E {
            get {
                return ResourceManager.GetString("M10009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此角色是否已经被使用！.
        /// </summary>
        public static string M10010E {
            get {
                return ResourceManager.GetString("M10010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入查询证件号码！.
        /// </summary>
        public static string M10011E {
            get {
                return ResourceManager.GetString("M10011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码错误！.
        /// </summary>
        public static string M10012E {
            get {
                return ResourceManager.GetString("M10012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原密码错误！.
        /// </summary>
        public static string M10013E {
            get {
                return ResourceManager.GetString("M10013E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有菜单正在被使用，不能移出！.
        /// </summary>
        public static string M10014E {
            get {
                return ResourceManager.GetString("M10014E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购明细单存在供应商信息不能删除.
        /// </summary>
        public static string M20001E {
            get {
                return ResourceManager.GetString("M20001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本次变更申请已经确认了！.
        /// </summary>
        public static string M20002E {
            get {
                return ResourceManager.GetString("M20002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间{0},已经被占用，无法进行户型变更，请确认！.
        /// </summary>
        public static string M20003E {
            get {
                return ResourceManager.GetString("M20003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购单已经确认，无需重复确认！.
        /// </summary>
        public static string M20004E {
            get {
                return ResourceManager.GetString("M20004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购单确认失败，请重试！.
        /// </summary>
        public static string M20005E {
            get {
                return ResourceManager.GetString("M20005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先添加采购单明细！.
        /// </summary>
        public static string M20006E {
            get {
                return ResourceManager.GetString("M20006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动资产添置失败，请重试！.
        /// </summary>
        public static string M20007E {
            get {
                return ResourceManager.GetString("M20007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动资产替换失败，请重试！.
        /// </summary>
        public static string M20008E {
            get {
                return ResourceManager.GetString("M20008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动资产移除失败，请重试！.
        /// </summary>
        public static string M20009E {
            get {
                return ResourceManager.GetString("M20009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目动资产添加失败，请重试！.
        /// </summary>
        public static string M20010E {
            get {
                return ResourceManager.GetString("M20010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幢动资产添加失败，请重试！.
        /// </summary>
        public static string M20011E {
            get {
                return ResourceManager.GetString("M20011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量删除室失败，请重试！.
        /// </summary>
        public static string M20012E {
            get {
                return ResourceManager.GetString("M20012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资产数量不足，无法进行分配！.
        /// </summary>
        public static string M20013E {
            get {
                return ResourceManager.GetString("M20013E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请在生成意向合同后,再缴费,最后签章！.
        /// </summary>
        public static string M20014E {
            get {
                return ResourceManager.GetString("M20014E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择部位信息。.
        /// </summary>
        public static string M20014I {
            get {
                return ResourceManager.GetString("M20014I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每层最大房间数量不能超过100间，请更改 “单元数”或 “每单元最大室数！.
        /// </summary>
        public static string M20015E {
            get {
                return ResourceManager.GetString("M20015E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先保存室基本信息。.
        /// </summary>
        public static string M20016I {
            get {
                return ResourceManager.GetString("M20016I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只能选择一条记录！.
        /// </summary>
        public static string M20017E {
            get {
                return ResourceManager.GetString("M20017E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先新增采购单明细！.
        /// </summary>
        public static string M20018I {
            get {
                return ResourceManager.GetString("M20018I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先保存户型基本信息！.
        /// </summary>
        public static string M20019I {
            get {
                return ResourceManager.GetString("M20019I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择部位信息！.
        /// </summary>
        public static string M20020I {
            get {
                return ResourceManager.GetString("M20020I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先新增或修改票据！.
        /// </summary>
        public static string M20021I {
            get {
                return ResourceManager.GetString("M20021I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此动资产是否已经被使用！.
        /// </summary>
        public static string M20022E {
            get {
                return ResourceManager.GetString("M20022E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此幢是否已经包含室！.
        /// </summary>
        public static string M20023E {
            get {
                return ResourceManager.GetString("M20023E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，此室下面已经有动资产，无法删除！.
        /// </summary>
        public static string M20024E {
            get {
                return ResourceManager.GetString("M20024E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，此部位下面已经有动资产，无法删除！.
        /// </summary>
        public static string M20025E {
            get {
                return ResourceManager.GetString("M20025E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此室是否已经被使用！.
        /// </summary>
        public static string M20026E {
            get {
                return ResourceManager.GetString("M20026E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，此采购单下已有采购明细！.
        /// </summary>
        public static string M20027E {
            get {
                return ResourceManager.GetString("M20027E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此采购单是否存在采购明细！.
        /// </summary>
        public static string M20028E {
            get {
                return ResourceManager.GetString("M20028E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此房源类型是否已经被使用！.
        /// </summary>
        public static string M20029E {
            get {
                return ResourceManager.GetString("M20029E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此户型是否已经被使用！.
        /// </summary>
        public static string M20030E {
            get {
                return ResourceManager.GetString("M20030E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此部位资产是否已经被使用！.
        /// </summary>
        public static string M20031E {
            get {
                return ResourceManager.GetString("M20031E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此部位是否已经被使用！.
        /// </summary>
        public static string M20032E {
            get {
                return ResourceManager.GetString("M20032E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购单已经确认，无法删除！.
        /// </summary>
        public static string M20033E {
            get {
                return ResourceManager.GetString("M20033E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此规格型号已经存在！.
        /// </summary>
        public static string M20034E {
            get {
                return ResourceManager.GetString("M20034E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此品牌已经存在！.
        /// </summary>
        public static string M20035E {
            get {
                return ResourceManager.GetString("M20035E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查此区域是否已经包含停车位！.
        /// </summary>
        public static string M20036E {
            get {
                return ResourceManager.GetString("M20036E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成合同失败，请重试！.
        /// </summary>
        public static string M30001E {
            get {
                return ResourceManager.GetString("M30001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合同无法进行作废！.
        /// </summary>
        public static string M30002E {
            get {
                return ResourceManager.GetString("M30002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合同作废失败，请稍后再试！.
        /// </summary>
        public static string M30003E {
            get {
                return ResourceManager.GetString("M30003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除申请信息失败，合同已经生成！.
        /// </summary>
        public static string M30004E {
            get {
                return ResourceManager.GetString("M30004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除申请信息失败，请稍后再试！.
        /// </summary>
        public static string M30005E {
            get {
                return ResourceManager.GetString("M30005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，请先选择要预订的房间！.
        /// </summary>
        public static string M30006E {
            get {
                return ResourceManager.GetString("M30006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预订金收取失败，请稍后再试！.
        /// </summary>
        public static string M30007E {
            get {
                return ResourceManager.GetString("M30007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对不起，此合同暂时无法作废。.
        /// </summary>
        public static string M30008E {
            get {
                return ResourceManager.GetString("M30008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此合同{0}房间未使用，需要扣除预订金{1}元，是否确认作废？.
        /// </summary>
        public static string M30009E {
            get {
                return ResourceManager.GetString("M30009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此企业存在正在结转的租户合同，无法进行作废！.
        /// </summary>
        public static string M30010E {
            get {
                return ResourceManager.GetString("M30010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核失败，请重试！.
        /// </summary>
        public static string M30011E {
            get {
                return ResourceManager.GetString("M30011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分配房间失败，请重试！.
        /// </summary>
        public static string M30012E {
            get {
                return ResourceManager.GetString("M30012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成合同失败，请重试！.
        /// </summary>
        public static string M30013E {
            get {
                return ResourceManager.GetString("M30013E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的房间已经被使用，请重新选择房间！.
        /// </summary>
        public static string M30014E {
            get {
                return ResourceManager.GetString("M30014E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 费用收取失败，请稍后再试！.
        /// </summary>
        public static string M30015E {
            get {
                return ResourceManager.GetString("M30015E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合同作废失败，请稍后重试！.
        /// </summary>
        public static string M30016E {
            get {
                return ResourceManager.GetString("M30016E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交合同审核失败，请稍后再试！.
        /// </summary>
        public static string M30017E {
            get {
                return ResourceManager.GetString("M30017E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入住登记失败，请重试！.
        /// </summary>
        public static string M30018E {
            get {
                return ResourceManager.GetString("M30018E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 续签合同生成失败，请重试！.
        /// </summary>
        public static string M30019E {
            get {
                return ResourceManager.GetString("M30019E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 续签合同作废失败，请重试！.
        /// </summary>
        public static string M30020E {
            get {
                return ResourceManager.GetString("M30020E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合同尚未分配房间，请先分配房间！.
        /// </summary>
        public static string M30021E {
            get {
                return ResourceManager.GetString("M30021E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合同信息尚不完全，请填写完整的合同信息！.
        /// </summary>
        public static string M30022E {
            get {
                return ResourceManager.GetString("M30022E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退租受理失败，请重试！.
        /// </summary>
        public static string M30023E {
            get {
                return ResourceManager.GetString("M30023E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退租登记信息不全，请先填写退租登记！.
        /// </summary>
        public static string M30024E {
            get {
                return ResourceManager.GetString("M30024E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交退租申请失败，请重试！.
        /// </summary>
        public static string M30025E {
            get {
                return ResourceManager.GetString("M30025E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 补缴费用保存失败，请重试！.
        /// </summary>
        public static string M30026E {
            get {
                return ResourceManager.GetString("M30026E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 费用收取失败，请重试！.
        /// </summary>
        public static string M30027E {
            get {
                return ResourceManager.GetString("M30027E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退租退房失败，请重试！.
        /// </summary>
        public static string M30028E {
            get {
                return ResourceManager.GetString("M30028E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退费失败，请重试！.
        /// </summary>
        public static string M30029E {
            get {
                return ResourceManager.GetString("M30029E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消退租失败，请重试！.
        /// </summary>
        public static string M30030E {
            get {
                return ResourceManager.GetString("M30030E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申请已成功提交，5个工作日内将给您通知。.
        /// </summary>
        public static string M30031E {
            get {
                return ResourceManager.GetString("M30031E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整租金失败，请重试！.
        /// </summary>
        public static string M30032E {
            get {
                return ResourceManager.GetString("M30032E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该个人信息已经提交，请不要重复提交！.
        /// </summary>
        public static string M30033E {
            get {
                return ResourceManager.GetString("M30033E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传的图片不能超过2M,请重新选择！.
        /// </summary>
        public static string M30034E {
            get {
                return ResourceManager.GetString("M30034E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在合同的合同期内，合同对应的房间已经被分配或者出租，暂时无法进行续签，请调整合同时间。.
        /// </summary>
        public static string M30035E {
            get {
                return ResourceManager.GetString("M30035E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在合同的合同期内，合同对应的房间已经被分配或者出租，暂时无法进行合同生成，请调整合同时间。.
        /// </summary>
        public static string M30036E {
            get {
                return ResourceManager.GetString("M30036E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请核实此合同编号的有效性和此合同已经是待签章状态。.
        /// </summary>
        public static string M30037E {
            get {
                return ResourceManager.GetString("M30037E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日常费用收取失败！.
        /// </summary>
        public static string M40001E {
            get {
                return ResourceManager.GetString("M40001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有需要汇总的记录！.
        /// </summary>
        public static string M40002E {
            get {
                return ResourceManager.GetString("M40002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 汇总失败，请重试！.
        /// </summary>
        public static string M40003E {
            get {
                return ResourceManager.GetString("M40003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有需要提交的记录！.
        /// </summary>
        public static string M40004E {
            get {
                return ResourceManager.GetString("M40004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交失败，请重试！.
        /// </summary>
        public static string M40005E {
            get {
                return ResourceManager.GetString("M40005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有需要审核的记录！.
        /// </summary>
        public static string M40006E {
            get {
                return ResourceManager.GetString("M40006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核失败，请重试！.
        /// </summary>
        public static string M40007E {
            get {
                return ResourceManager.GetString("M40007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有需要退回的记录！.
        /// </summary>
        public static string M40008E {
            get {
                return ResourceManager.GetString("M40008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退回失败，请重试！.
        /// </summary>
        public static string M40009E {
            get {
                return ResourceManager.GetString("M40009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请对上个月进行封帐！.
        /// </summary>
        public static string M40010E {
            get {
                return ResourceManager.GetString("M40010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当月还有未核帐的数据，请全部核帐后，在进行封帐操作！.
        /// </summary>
        public static string M40011E {
            get {
                return ResourceManager.GetString("M40011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封帐失败，请重试！.
        /// </summary>
        public static string M40012E {
            get {
                return ResourceManager.GetString("M40012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有需要封帐的记录！.
        /// </summary>
        public static string M40013E {
            get {
                return ResourceManager.GetString("M40013E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一个正常使用的票据进行作废！.
        /// </summary>
        public static string M50001E {
            get {
                return ResourceManager.GetString("M50001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 票据作废失败！.
        /// </summary>
        public static string M50002E {
            get {
                return ResourceManager.GetString("M50002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请对已作废的进行红冲！.
        /// </summary>
        public static string M50003E {
            get {
                return ResourceManager.GetString("M50003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该票据已经被红冲过！.
        /// </summary>
        public static string M50004E {
            get {
                return ResourceManager.GetString("M50004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前没有可用于红冲的票据本，请领用新的票据！.
        /// </summary>
        public static string M50005E {
            get {
                return ResourceManager.GetString("M50005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择已作废的票据进行更正！.
        /// </summary>
        public static string M50006E {
            get {
                return ResourceManager.GetString("M50006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该票据已经被更正过，不能重复更正！.
        /// </summary>
        public static string M50007E {
            get {
                return ResourceManager.GetString("M50007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前没有可用于更正的票据本，请领用新的票据！.
        /// </summary>
        public static string M50008E {
            get {
                return ResourceManager.GetString("M50008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查此税控卡是否使用完毕！.
        /// </summary>
        public static string M50009E {
            get {
                return ResourceManager.GetString("M50009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败，请检查票据是否被使用！.
        /// </summary>
        public static string M50010E {
            get {
                return ResourceManager.GetString("M50010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该税控卡所维护的发票本已达上限，不能再维护了！.
        /// </summary>
        public static string M50011E {
            get {
                return ResourceManager.GetString("M50011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该发票本还未使用完！.
        /// </summary>
        public static string M50012E {
            get {
                return ResourceManager.GetString("M50012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过租用时长！.
        /// </summary>
        public static string M50013E {
            get {
                return ResourceManager.GetString("M50013E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 租用时长期限不匹配！.
        /// </summary>
        public static string M50014E {
            get {
                return ResourceManager.GetString("M50014E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前没有可用于红冲的票据本，请领用新的票据！.
        /// </summary>
        public static string M50015E {
            get {
                return ResourceManager.GetString("M50015E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写相应的租用时间和租用费用！.
        /// </summary>
        public static string M50016E {
            get {
                return ResourceManager.GetString("M50016E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先红冲后在更正票据！.
        /// </summary>
        public static string M50017E {
            get {
                return ResourceManager.GetString("M50017E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能对未使用票据进行红冲！.
        /// </summary>
        public static string M50018E {
            get {
                return ResourceManager.GetString("M50018E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该审批人已经存在，不能重复添加！.
        /// </summary>
        public static string M60001E {
            get {
                return ResourceManager.GetString("M60001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该关卡不可会签，不能添加多个审批人！.
        /// </summary>
        public static string M60002E {
            get {
                return ResourceManager.GetString("M60002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该关卡有多个审批人，不能改成非会签！.
        /// </summary>
        public static string M60003E {
            get {
                return ResourceManager.GetString("M60003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查合同相关信息是否填写完整！.
        /// </summary>
        public static string M60004E {
            get {
                return ResourceManager.GetString("M60004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此意向合同存在正在结转的商铺合同，无法进行作废！.
        /// </summary>
        public static string M60005E {
            get {
                return ResourceManager.GetString("M60005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您所要删除的商铺中至少有一个商铺正在被使用，无法做删除操作！.
        /// </summary>
        public static string M60006E {
            get {
                return ResourceManager.GetString("M60006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查房间是否选择！.
        /// </summary>
        public static string M60007E {
            get {
                return ResourceManager.GetString("M60007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查该合同是否有忘记已出租！.
        /// </summary>
        public static string M60008E {
            get {
                return ResourceManager.GetString("M60008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成合同失败，请先分配房间！.
        /// </summary>
        public static string M60009E {
            get {
                return ResourceManager.GetString("M60009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除操作失败，请确认该项目下是否有幢信息！.
        /// </summary>
        public static string M60010E {
            get {
                return ResourceManager.GetString("M60010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此菜单下已有菜单信息，无法做删除操作；请确保此菜单下无菜单信息后，再做删除操作！.
        /// </summary>
        public static string M60011E {
            get {
                return ResourceManager.GetString("M60011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此菜单在角色权限中已分配，无法做删除操作；请确保此菜单没被使用，再做删除操作！.
        /// </summary>
        public static string M60012E {
            get {
                return ResourceManager.GetString("M60012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此菜单在用户权限中已分配，无法做删除操作；请确保此菜单没被使用，再做删除操作！.
        /// </summary>
        public static string M60013E {
            get {
                return ResourceManager.GetString("M60013E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认该企业下所有申请人审核完成！.
        /// </summary>
        public static string M70001E {
            get {
                return ResourceManager.GetString("M70001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此申请单的主申请人审核不通过，无法继续审核共同申请人！.
        /// </summary>
        public static string M70002E {
            get {
                return ResourceManager.GetString("M70002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先设置该小区该房间类型的预定金，在进行操作！.
        /// </summary>
        public static string M70003E {
            get {
                return ResourceManager.GetString("M70003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该类型房间已经分配满！.
        /// </summary>
        public static string M70004E {
            get {
                return ResourceManager.GetString("M70004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 先分配人员后在设置房间管理员！.
        /// </summary>
        public static string M70005E {
            get {
                return ResourceManager.GetString("M70005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请全部审核完成后在确认审核结果！.
        /// </summary>
        public static string M70006E {
            get {
                return ResourceManager.GetString("M70006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择所有房间审核数量！.
        /// </summary>
        public static string M70007E {
            get {
                return ResourceManager.GetString("M70007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先审核未审核的家庭成员！然后在确认审核结果！.
        /// </summary>
        public static string M70008E {
            get {
                return ResourceManager.GetString("M70008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先给每个房间设置银行卡号，在进行操作！.
        /// </summary>
        public static string M70009E {
            get {
                return ResourceManager.GetString("M70009E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先确认是否还有未验的房间，在进行操作！.
        /// </summary>
        public static string M70010E {
            get {
                return ResourceManager.GetString("M70010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先生成合同后再打印！.
        /// </summary>
        public static string M70011E {
            get {
                return ResourceManager.GetString("M70011E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该企业已经确认复审结果完成！.
        /// </summary>
        public static string M70012E {
            get {
                return ResourceManager.GetString("M70012E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择需要退租的房间!.
        /// </summary>
        public static string M70013E {
            get {
                return ResourceManager.GetString("M70013E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传的图片不能超过300K,请重新选择！.
        /// </summary>
        public static string M70014E {
            get {
                return ResourceManager.GetString("M70014E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您已预定过房源信息，请不要重复预定。.
        /// </summary>
        public static string M70015E {
            get {
                return ResourceManager.GetString("M70015E", resourceCulture);
            }
        }
    }
}
