//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.155.225;Initial Catalog=LJZGZFWeb;Persist Security Info=True;" +
            "User ID=ljzgzf;Password=ljzgzf;")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
            set {
                this["SqlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNRegex")]
        public string NamespacePrefix {
            get {
                return ((string)(this["NamespacePrefix"]));
            }
            set {
                this["NamespacePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\CNRegex\\")]
        public string ProjectRootPath {
            get {
                return ((string)(this["ProjectRootPath"]));
            }
            set {
                this["ProjectRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNRegex.Dal")]
        public string DalFolder {
            get {
                return ((string)(this["DalFolder"]));
            }
            set {
                this["DalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNRegex.Biz")]
        public string BizFolder {
            get {
                return ((string)(this["BizFolder"]));
            }
            set {
                this["BizFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNRegex.Entity")]
        public string EntityFolder {
            get {
                return ((string)(this["EntityFolder"]));
            }
            set {
                this["EntityFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNRegex.Enum")]
        public string EnumFolder {
            get {
                return ((string)(this["EnumFolder"]));
            }
            set {
                this["EnumFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ip:8080/tfs")]
        public string TFSUrl {
            get {
                return ((string)(this["TFSUrl"]));
            }
            set {
                this["TFSUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user name")]
        public string TFSName {
            get {
                return ((string)(this["TFSName"]));
            }
            set {
                this["TFSName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user password")]
        public string TFSPassword {
            get {
                return ((string)(this["TFSPassword"]));
            }
            set {
                this["TFSPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string TFSChk {
            get {
                return ((string)(this["TFSChk"]));
            }
            set {
                this["TFSChk"] = value;
            }
        }
    }
}
